use Mix.Config

config :admint,
  ecto_repos: [Admint.Demo.Repo],
  otp_app: :admint,
  ecto_repo: Admint.Demo.Repo,
  router: AdmintWeb.Demo.Router

# Configures the endpoint
config :admint, AdmintWeb.Demo.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "dcaIp9/8abWLt/f0x6Rn8ymumOHwHsB+g/v3CnYIAoe+gYuk//spZWxYJH/U8OLH",
  render_errors: [view: AdmintWeb.Demo.ErrorView, accepts: ~w(html json), layout: false],
  pubsub_server: Admint.Demo.PubSub,
  live_view: [signing_salt: "0D0yeLGi"]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Configure your database
config :admint, Admint.Demo.Repo,
  username: "postgres",
  password: "postgres",
  database: "admint_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :admint, AdmintWeb.Demo.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :admint, AdmintWeb.Demo.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"demo/admint_web/(live|views)/.*(ex)$",
      ~r"demo/admint_web/templates/.*(eex)$",
      ~r"lib/admint_web/(live|views)/.*(ex)$",
      ~r"lib/admint_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
